Version=1
# 10664.787109375
WorldMap.CenterX=10664.787109375

# 10381.9775390625
WorldMap.CenterY=10381.9775390625

# true
WorldMap.HighlightStreet=true

# true
WorldMap.Isometric=true

# true
WorldMap.LargeStreetLabel=true

# true
WorldMap.PlaceNames=true

# false
WorldMap.Players=false

# false
WorldMap.ShowPrintMedia=false

# true
WorldMap.ShowStreetNames=true

# true
WorldMap.ShowSymbolsUI=true

# true
WorldMap.Symbols=true

# false
WorldMap.TerrainImage=false

# 17.0
WorldMap.Zoom=17.0

# 19.0
MiniMap.Zoom=19.0

# true
MiniMap.Isometric=true

# false
MiniMap.ShowSymbols=false

# true
MiniMap.StartVisible=true

# false
MiniMap.TerrainImage=false