Version=1
# 8136.5234375
WorldMap.CenterX=8136.5234375

# 11491.0439453125
WorldMap.CenterY=11491.0439453125

# true
WorldMap.HighlightStreet=true

# true
WorldMap.Isometric=true

# true
WorldMap.LargeStreetLabel=true

# true
WorldMap.PlaceNames=true

# false
WorldMap.Players=false

# false
WorldMap.ShowPrintMedia=false

# true
WorldMap.ShowStreetNames=true

# true
WorldMap.ShowSymbolsUI=true

# true
WorldMap.Symbols=true

# false
WorldMap.TerrainImage=false

# 17.5
WorldMap.Zoom=17.5

# 12.5
MiniMap.Zoom=12.5

# true
MiniMap.Isometric=true

# true
MiniMap.ShowSymbols=true

# true
MiniMap.StartVisible=true

# false
MiniMap.TerrainImage=false