Version=1
# 6880.0234375
WorldMap.CenterX=6880.0234375

# 11497.966796875
WorldMap.CenterY=11497.966796875

# true
WorldMap.HighlightStreet=true

# true
WorldMap.Isometric=true

# true
WorldMap.LargeStreetLabel=true

# true
WorldMap.PlaceNames=true

# false
WorldMap.Players=false

# true
WorldMap.ShowPrintMedia=true

# true
WorldMap.ShowStreetNames=true

# true
WorldMap.ShowSymbolsUI=true

# true
WorldMap.Symbols=true

# false
WorldMap.TerrainImage=false

# 13.0
WorldMap.Zoom=13.0

# 12.0
MiniMap.Zoom=12.0

# true
MiniMap.Isometric=true

# true
MiniMap.ShowSymbols=true

# true
MiniMap.StartVisible=true

# false
MiniMap.TerrainImage=false